sudo: required
services:
- docker
language: bash
script:
# prepare qemu
- docker run --rm --privileged multiarch/qemu-user-static:register --reset
# build image
- docker build -t unre4l/mongo-arm .
# test image
- docker run unre4l/mongo-arm mongod --version
# push image
- >
  if [ "$TRAVIS_BRANCH" == "master" ] && [ "$TRAVIS_PULL_REQUEST" == "false" ]; then
    docker login -u="$DOCKER_USER" -p="$DOCKER_PASS"
    TAG=$(grep "ENV MONGO_VERSION" Dockerfile | awk 'NF>1{print $NF}')
    docker tag unre4l/mongo-arm unre4l/mongo-arm:$TAG
    docker push unre4l/mongo-arm:$TAG
    docker push unre4l/mongo-arm
  fi